// action - customization reducer
export const SET_MENU = '@customization/SET_MENU';
export const MENU_TOGGLE = '@customization/MENU_TOGGLE';
export const MENU_OPEN = '@customization/MENU_OPEN';
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';
export const SET_TEXT = '@customization/SET_TEXT';
export const SET_SHOW_STEPS = '@customization/SET_SHOW_STEPS';
export const SET_SHOW_SLEEP = '@customization/SET_SHOW_SLEEP';
export const SET_SHOW_SEDENTARY = '@customization/SET_SHOW_SEDENTARY';
export const SET_SHOW_ACTIVITY = '@customization/SET_SHOW_ACTIVITY';
export const SET_PERIOD = '@customization/SET_PERIOD';
